// Code generated by go-swagger; DO NOT EDIT.

package datasources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// UpsertDatasourceReader is a Reader for the UpsertDatasource structure.
type UpsertDatasourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpsertDatasourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpsertDatasourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewUpsertDatasourceNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpsertDatasourceOK creates a UpsertDatasourceOK with default headers values
func NewUpsertDatasourceOK() *UpsertDatasourceOK {
	return &UpsertDatasourceOK{}
}

/* UpsertDatasourceOK describes a response with status code 200, with default header values.

OK
*/
type UpsertDatasourceOK struct {

	/* The ETag (or entity tag) HTTP response header is an identifier for a specific version of a resource. See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag> documentation.
	 */
	Etag string

	Payload *models.DatasourcesV1DatasourcesPutResponse
}

func (o *UpsertDatasourceOK) Error() string {
	return fmt.Sprintf("[PUT /v1/datasources/{datasource}][%d] upsertDatasourceOK  %+v", 200, o.Payload)
}
func (o *UpsertDatasourceOK) GetPayload() *models.DatasourcesV1DatasourcesPutResponse {
	return o.Payload
}

func (o *UpsertDatasourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Etag
	hdrEtag := response.GetHeader("Etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	o.Payload = new(models.DatasourcesV1DatasourcesPutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpsertDatasourceNotModified creates a UpsertDatasourceNotModified with default headers values
func NewUpsertDatasourceNotModified() *UpsertDatasourceNotModified {
	return &UpsertDatasourceNotModified{}
}

/* UpsertDatasourceNotModified describes a response with status code 304, with default header values.

Not Modified
*/
type UpsertDatasourceNotModified struct {
}

func (o *UpsertDatasourceNotModified) Error() string {
	return fmt.Sprintf("[PUT /v1/datasources/{datasource}][%d] upsertDatasourceNotModified ", 304)
}

func (o *UpsertDatasourceNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
