// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDataParams creates a new GetDataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataParams() *GetDataParams {
	return &GetDataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataParamsWithTimeout creates a new GetDataParams object
// with the ability to set a timeout on a request.
func NewGetDataParamsWithTimeout(timeout time.Duration) *GetDataParams {
	return &GetDataParams{
		timeout: timeout,
	}
}

// NewGetDataParamsWithContext creates a new GetDataParams object
// with the ability to set a context for a request.
func NewGetDataParamsWithContext(ctx context.Context) *GetDataParams {
	return &GetDataParams{
		Context: ctx,
	}
}

// NewGetDataParamsWithHTTPClient creates a new GetDataParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataParamsWithHTTPClient(client *http.Client) *GetDataParams {
	return &GetDataParams{
		HTTPClient: client,
	}
}

/* GetDataParams contains all the parameters to send to the API endpoint
   for the get data operation.

   Typically these are written to a http.Request.
*/
type GetDataParams struct {

	/* IfNoneMatch.

	   The server will return the requested resource, with a 200 status, only if it doesn't have an ETag matching the given ones. See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match> documentation.
	*/
	IfNoneMatch *string

	/* Download.

	   Download data as <name>.json file
	*/
	Download *bool

	/* Jsonpath.

	   Json Path expression to extract portions of documents
	*/
	Jsonpath *string

	/* Limit.

	     Returns '413 Payload Too Large' response if the body size is greater than given limit.
	The units KB, MB and etc can be used.
	Example: 10 MB; 28 kilobytes; 2000
	*/
	Limit *string

	/* Name.

	   data name
	*/
	Name string

	/* Rego.

	   Rego query to be executed for the documents
	*/
	Rego *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataParams) WithDefaults() *GetDataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataParams) SetDefaults() {
	var (
		downloadDefault = bool(false)
	)

	val := GetDataParams{
		Download: &downloadDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get data params
func (o *GetDataParams) WithTimeout(timeout time.Duration) *GetDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data params
func (o *GetDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data params
func (o *GetDataParams) WithContext(ctx context.Context) *GetDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data params
func (o *GetDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data params
func (o *GetDataParams) WithHTTPClient(client *http.Client) *GetDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data params
func (o *GetDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfNoneMatch adds the ifNoneMatch to the get data params
func (o *GetDataParams) WithIfNoneMatch(ifNoneMatch *string) *GetDataParams {
	o.SetIfNoneMatch(ifNoneMatch)
	return o
}

// SetIfNoneMatch adds the ifNoneMatch to the get data params
func (o *GetDataParams) SetIfNoneMatch(ifNoneMatch *string) {
	o.IfNoneMatch = ifNoneMatch
}

// WithDownload adds the download to the get data params
func (o *GetDataParams) WithDownload(download *bool) *GetDataParams {
	o.SetDownload(download)
	return o
}

// SetDownload adds the download to the get data params
func (o *GetDataParams) SetDownload(download *bool) {
	o.Download = download
}

// WithJsonpath adds the jsonpath to the get data params
func (o *GetDataParams) WithJsonpath(jsonpath *string) *GetDataParams {
	o.SetJsonpath(jsonpath)
	return o
}

// SetJsonpath adds the jsonpath to the get data params
func (o *GetDataParams) SetJsonpath(jsonpath *string) {
	o.Jsonpath = jsonpath
}

// WithLimit adds the limit to the get data params
func (o *GetDataParams) WithLimit(limit *string) *GetDataParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get data params
func (o *GetDataParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithName adds the name to the get data params
func (o *GetDataParams) WithName(name string) *GetDataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get data params
func (o *GetDataParams) SetName(name string) {
	o.Name = name
}

// WithRego adds the rego to the get data params
func (o *GetDataParams) WithRego(rego *string) *GetDataParams {
	o.SetRego(rego)
	return o
}

// SetRego adds the rego to the get data params
func (o *GetDataParams) SetRego(rego *string) {
	o.Rego = rego
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfNoneMatch != nil {

		// header param If-None-Match
		if err := r.SetHeaderParam("If-None-Match", *o.IfNoneMatch); err != nil {
			return err
		}
	}

	if o.Download != nil {

		// query param download
		var qrDownload bool

		if o.Download != nil {
			qrDownload = *o.Download
		}
		qDownload := swag.FormatBool(qrDownload)
		if qDownload != "" {

			if err := r.SetQueryParam("download", qDownload); err != nil {
				return err
			}
		}
	}

	if o.Jsonpath != nil {

		// query param jsonpath
		var qrJsonpath string

		if o.Jsonpath != nil {
			qrJsonpath = *o.Jsonpath
		}
		qJsonpath := qrJsonpath
		if qJsonpath != "" {

			if err := r.SetQueryParam("jsonpath", qJsonpath); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Rego != nil {

		// query param rego
		var qrRego string

		if o.Rego != nil {
			qrRego = *o.Rego
		}
		qRego := qrRego
		if qRego != "" {

			if err := r.SetQueryParam("rego", qRego); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
