// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// GetDataReader is a Reader for the GetData structure.
type GetDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetDataNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewGetDataRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDataOK creates a GetDataOK with default headers values
func NewGetDataOK() *GetDataOK {
	return &GetDataOK{}
}

/* GetDataOK describes a response with status code 200, with default header values.

OK
*/
type GetDataOK struct {

	/* The ETag (or entity tag) HTTP response header is an identifier for a specific version of a resource. See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag> documentation.
	 */
	Etag string

	Payload *models.DataV1DataResponse
}

func (o *GetDataOK) Error() string {
	return fmt.Sprintf("[GET /v1/data/{name}][%d] getDataOK  %+v", 200, o.Payload)
}
func (o *GetDataOK) GetPayload() *models.DataV1DataResponse {
	return o.Payload
}

func (o *GetDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Etag
	hdrEtag := response.GetHeader("Etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	o.Payload = new(models.DataV1DataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataNotModified creates a GetDataNotModified with default headers values
func NewGetDataNotModified() *GetDataNotModified {
	return &GetDataNotModified{}
}

/* GetDataNotModified describes a response with status code 304, with default header values.

Not Modified
*/
type GetDataNotModified struct {
}

func (o *GetDataNotModified) Error() string {
	return fmt.Sprintf("[GET /v1/data/{name}][%d] getDataNotModified ", 304)
}

func (o *GetDataNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDataNotFound creates a GetDataNotFound with default headers values
func NewGetDataNotFound() *GetDataNotFound {
	return &GetDataNotFound{}
}

/* GetDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetDataNotFound struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *GetDataNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/data/{name}][%d] getDataNotFound  %+v", 404, o.Payload)
}
func (o *GetDataNotFound) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *GetDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataRequestEntityTooLarge creates a GetDataRequestEntityTooLarge with default headers values
func NewGetDataRequestEntityTooLarge() *GetDataRequestEntityTooLarge {
	return &GetDataRequestEntityTooLarge{}
}

/* GetDataRequestEntityTooLarge describes a response with status code 413, with default header values.

Request Entity Too Large
*/
type GetDataRequestEntityTooLarge struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *GetDataRequestEntityTooLarge) Error() string {
	return fmt.Sprintf("[GET /v1/data/{name}][%d] getDataRequestEntityTooLarge  %+v", 413, o.Payload)
}
func (o *GetDataRequestEntityTooLarge) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *GetDataRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
