// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// HeadListDataReader is a Reader for the HeadListData structure.
type HeadListDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadListDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadListDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewHeadListDataNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewHeadListDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHeadListDataOK creates a HeadListDataOK with default headers values
func NewHeadListDataOK() *HeadListDataOK {
	return &HeadListDataOK{}
}

/* HeadListDataOK describes a response with status code 200, with default header values.

OK
*/
type HeadListDataOK struct {

	/* The ETag (or entity tag) HTTP response header is an identifier for a specific version of a resource. See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag> documentation.
	 */
	Etag string
}

func (o *HeadListDataOK) Error() string {
	return fmt.Sprintf("[HEAD /v1/data][%d] headListDataOK ", 200)
}

func (o *HeadListDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Etag
	hdrEtag := response.GetHeader("Etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	return nil
}

// NewHeadListDataNotModified creates a HeadListDataNotModified with default headers values
func NewHeadListDataNotModified() *HeadListDataNotModified {
	return &HeadListDataNotModified{}
}

/* HeadListDataNotModified describes a response with status code 304, with default header values.

Not Modified
*/
type HeadListDataNotModified struct {
}

func (o *HeadListDataNotModified) Error() string {
	return fmt.Sprintf("[HEAD /v1/data][%d] headListDataNotModified ", 304)
}

func (o *HeadListDataNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHeadListDataNotFound creates a HeadListDataNotFound with default headers values
func NewHeadListDataNotFound() *HeadListDataNotFound {
	return &HeadListDataNotFound{}
}

/* HeadListDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type HeadListDataNotFound struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *HeadListDataNotFound) Error() string {
	return fmt.Sprintf("[HEAD /v1/data][%d] headListDataNotFound  %+v", 404, o.Payload)
}
func (o *HeadListDataNotFound) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *HeadListDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
