// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// ListDataReader is a Reader for the ListData structure.
type ListDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewListDataNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewListDataRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListDataOK creates a ListDataOK with default headers values
func NewListDataOK() *ListDataOK {
	return &ListDataOK{}
}

/* ListDataOK describes a response with status code 200, with default header values.

OK
*/
type ListDataOK struct {

	/* The ETag (or entity tag) HTTP response header is an identifier for a specific version of a resource. See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag> documentation.
	 */
	Etag string

	Payload *models.DataV1DataResponse
}

func (o *ListDataOK) Error() string {
	return fmt.Sprintf("[GET /v1/data][%d] listDataOK  %+v", 200, o.Payload)
}
func (o *ListDataOK) GetPayload() *models.DataV1DataResponse {
	return o.Payload
}

func (o *ListDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Etag
	hdrEtag := response.GetHeader("Etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	o.Payload = new(models.DataV1DataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDataNotModified creates a ListDataNotModified with default headers values
func NewListDataNotModified() *ListDataNotModified {
	return &ListDataNotModified{}
}

/* ListDataNotModified describes a response with status code 304, with default header values.

Not Modified
*/
type ListDataNotModified struct {
}

func (o *ListDataNotModified) Error() string {
	return fmt.Sprintf("[GET /v1/data][%d] listDataNotModified ", 304)
}

func (o *ListDataNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListDataNotFound creates a ListDataNotFound with default headers values
func NewListDataNotFound() *ListDataNotFound {
	return &ListDataNotFound{}
}

/* ListDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListDataNotFound struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *ListDataNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/data][%d] listDataNotFound  %+v", 404, o.Payload)
}
func (o *ListDataNotFound) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *ListDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDataRequestEntityTooLarge creates a ListDataRequestEntityTooLarge with default headers values
func NewListDataRequestEntityTooLarge() *ListDataRequestEntityTooLarge {
	return &ListDataRequestEntityTooLarge{}
}

/* ListDataRequestEntityTooLarge describes a response with status code 413, with default header values.

Request Entity Too Large
*/
type ListDataRequestEntityTooLarge struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *ListDataRequestEntityTooLarge) Error() string {
	return fmt.Sprintf("[GET /v1/data][%d] listDataRequestEntityTooLarge  %+v", 413, o.Payload)
}
func (o *ListDataRequestEntityTooLarge) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *ListDataRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
