// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// KafkaVerifyConfigReader is a Reader for the KafkaVerifyConfig structure.
type KafkaVerifyConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafkaVerifyConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafkaVerifyConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKafkaVerifyConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewKafkaVerifyConfigOK creates a KafkaVerifyConfigOK with default headers values
func NewKafkaVerifyConfigOK() *KafkaVerifyConfigOK {
	return &KafkaVerifyConfigOK{}
}

/* KafkaVerifyConfigOK describes a response with status code 200, with default header values.

OK
*/
type KafkaVerifyConfigOK struct {
	Payload *models.WorkspaceV1KafkaVerifyResponse
}

func (o *KafkaVerifyConfigOK) Error() string {
	return fmt.Sprintf("[POST /v1/workspace/kafka/verify-config][%d] kafkaVerifyConfigOK  %+v", 200, o.Payload)
}
func (o *KafkaVerifyConfigOK) GetPayload() *models.WorkspaceV1KafkaVerifyResponse {
	return o.Payload
}

func (o *KafkaVerifyConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WorkspaceV1KafkaVerifyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafkaVerifyConfigBadRequest creates a KafkaVerifyConfigBadRequest with default headers values
func NewKafkaVerifyConfigBadRequest() *KafkaVerifyConfigBadRequest {
	return &KafkaVerifyConfigBadRequest{}
}

/* KafkaVerifyConfigBadRequest describes a response with status code 400, with default header values.

Invalid Parameter
*/
type KafkaVerifyConfigBadRequest struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *KafkaVerifyConfigBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/workspace/kafka/verify-config][%d] kafkaVerifyConfigBadRequest  %+v", 400, o.Payload)
}
func (o *KafkaVerifyConfigBadRequest) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *KafkaVerifyConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
