// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// GetPoliciesReader is a Reader for the GetPolicies structure.
type GetPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetPoliciesNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPoliciesOK creates a GetPoliciesOK with default headers values
func NewGetPoliciesOK() *GetPoliciesOK {
	return &GetPoliciesOK{}
}

/* GetPoliciesOK describes a response with status code 200, with default header values.

OK
*/
type GetPoliciesOK struct {
	Payload *models.PoliciesV2PoliciesGetResponse
}

func (o *GetPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /v2/policies][%d] getPoliciesOK  %+v", 200, o.Payload)
}
func (o *GetPoliciesOK) GetPayload() *models.PoliciesV2PoliciesGetResponse {
	return o.Payload
}

func (o *GetPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PoliciesV2PoliciesGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPoliciesNotModified creates a GetPoliciesNotModified with default headers values
func NewGetPoliciesNotModified() *GetPoliciesNotModified {
	return &GetPoliciesNotModified{}
}

/* GetPoliciesNotModified describes a response with status code 304, with default header values.

Not Modified
*/
type GetPoliciesNotModified struct {
}

func (o *GetPoliciesNotModified) Error() string {
	return fmt.Sprintf("[GET /v2/policies][%d] getPoliciesNotModified ", 304)
}

func (o *GetPoliciesNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
