// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// GetPoliciesAtPathReader is a Reader for the GetPoliciesAtPath structure.
type GetPoliciesAtPathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPoliciesAtPathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPoliciesAtPathOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetPoliciesAtPathNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPoliciesAtPathOK creates a GetPoliciesAtPathOK with default headers values
func NewGetPoliciesAtPathOK() *GetPoliciesAtPathOK {
	return &GetPoliciesAtPathOK{}
}

/* GetPoliciesAtPathOK describes a response with status code 200, with default header values.

OK
*/
type GetPoliciesAtPathOK struct {
	Payload *models.PoliciesV2PoliciesGetResponse
}

func (o *GetPoliciesAtPathOK) Error() string {
	return fmt.Sprintf("[GET /v2/policies/{path}][%d] getPoliciesAtPathOK  %+v", 200, o.Payload)
}
func (o *GetPoliciesAtPathOK) GetPayload() *models.PoliciesV2PoliciesGetResponse {
	return o.Payload
}

func (o *GetPoliciesAtPathOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PoliciesV2PoliciesGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPoliciesAtPathNotModified creates a GetPoliciesAtPathNotModified with default headers values
func NewGetPoliciesAtPathNotModified() *GetPoliciesAtPathNotModified {
	return &GetPoliciesAtPathNotModified{}
}

/* GetPoliciesAtPathNotModified describes a response with status code 304, with default header values.

Not Modified
*/
type GetPoliciesAtPathNotModified struct {
}

func (o *GetPoliciesAtPathNotModified) Error() string {
	return fmt.Sprintf("[GET /v2/policies/{path}][%d] getPoliciesAtPathNotModified ", 304)
}

func (o *GetPoliciesAtPathNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
