// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListPlaygroundPoliciesParams creates a new ListPlaygroundPoliciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPlaygroundPoliciesParams() *ListPlaygroundPoliciesParams {
	return &ListPlaygroundPoliciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPlaygroundPoliciesParamsWithTimeout creates a new ListPlaygroundPoliciesParams object
// with the ability to set a timeout on a request.
func NewListPlaygroundPoliciesParamsWithTimeout(timeout time.Duration) *ListPlaygroundPoliciesParams {
	return &ListPlaygroundPoliciesParams{
		timeout: timeout,
	}
}

// NewListPlaygroundPoliciesParamsWithContext creates a new ListPlaygroundPoliciesParams object
// with the ability to set a context for a request.
func NewListPlaygroundPoliciesParamsWithContext(ctx context.Context) *ListPlaygroundPoliciesParams {
	return &ListPlaygroundPoliciesParams{
		Context: ctx,
	}
}

// NewListPlaygroundPoliciesParamsWithHTTPClient creates a new ListPlaygroundPoliciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPlaygroundPoliciesParamsWithHTTPClient(client *http.Client) *ListPlaygroundPoliciesParams {
	return &ListPlaygroundPoliciesParams{
		HTTPClient: client,
	}
}

/* ListPlaygroundPoliciesParams contains all the parameters to send to the API endpoint
   for the list playground policies operation.

   Typically these are written to a http.Request.
*/
type ListPlaygroundPoliciesParams struct {

	/* Drafts.

	   return rego metadata for draft policies (when metadata flag is used)
	*/
	Drafts *bool

	/* Metadata.

	   return rego metadata of specified type or all if no type provided
	*/
	Metadata *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list playground policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPlaygroundPoliciesParams) WithDefaults() *ListPlaygroundPoliciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list playground policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPlaygroundPoliciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list playground policies params
func (o *ListPlaygroundPoliciesParams) WithTimeout(timeout time.Duration) *ListPlaygroundPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list playground policies params
func (o *ListPlaygroundPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list playground policies params
func (o *ListPlaygroundPoliciesParams) WithContext(ctx context.Context) *ListPlaygroundPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list playground policies params
func (o *ListPlaygroundPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list playground policies params
func (o *ListPlaygroundPoliciesParams) WithHTTPClient(client *http.Client) *ListPlaygroundPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list playground policies params
func (o *ListPlaygroundPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDrafts adds the drafts to the list playground policies params
func (o *ListPlaygroundPoliciesParams) WithDrafts(drafts *bool) *ListPlaygroundPoliciesParams {
	o.SetDrafts(drafts)
	return o
}

// SetDrafts adds the drafts to the list playground policies params
func (o *ListPlaygroundPoliciesParams) SetDrafts(drafts *bool) {
	o.Drafts = drafts
}

// WithMetadata adds the metadata to the list playground policies params
func (o *ListPlaygroundPoliciesParams) WithMetadata(metadata *string) *ListPlaygroundPoliciesParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the list playground policies params
func (o *ListPlaygroundPoliciesParams) SetMetadata(metadata *string) {
	o.Metadata = metadata
}

// WriteToRequest writes these params to a swagger request
func (o *ListPlaygroundPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Drafts != nil {

		// query param drafts
		var qrDrafts bool

		if o.Drafts != nil {
			qrDrafts = *o.Drafts
		}
		qDrafts := swag.FormatBool(qrDrafts)
		if qDrafts != "" {

			if err := r.SetQueryParam("drafts", qDrafts); err != nil {
				return err
			}
		}
	}

	if o.Metadata != nil {

		// query param metadata
		var qrMetadata string

		if o.Metadata != nil {
			qrMetadata = *o.Metadata
		}
		qMetadata := qrMetadata
		if qMetadata != "" {

			if err := r.SetQueryParam("metadata", qMetadata); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
