// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mathianasj/terraform-provider-das/models"
)

// PromotePoliciesReader is a Reader for the PromotePolicies structure.
type PromotePoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PromotePoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPromotePoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPromotePoliciesOK creates a PromotePoliciesOK with default headers values
func NewPromotePoliciesOK() *PromotePoliciesOK {
	return &PromotePoliciesOK{}
}

/* PromotePoliciesOK describes a response with status code 200, with default header values.

OK
*/
type PromotePoliciesOK struct {
	Payload *models.PoliciesV2PoliciesPutResponse
}

func (o *PromotePoliciesOK) Error() string {
	return fmt.Sprintf("[PUT /v2/policies/{path}][%d] promotePoliciesOK  %+v", 200, o.Payload)
}
func (o *PromotePoliciesOK) GetPayload() *models.PoliciesV2PoliciesPutResponse {
	return o.Payload
}

func (o *PromotePoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PoliciesV2PoliciesPutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
