// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PoliciesV2RegoMetadata policies v2 rego metadata
//
// swagger:model policies.v2.RegoMetadata
type PoliciesV2RegoMetadata struct {

	// metadata
	Metadata map[string]PoliciesV2RuleMetadata `json:"metadata,omitempty"`

	// rules
	Rules map[string]PoliciesV2RegoMetadataSet `json:"rules,omitempty"`
}

// Validate validates this policies v2 rego metadata
func (m *PoliciesV2RegoMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PoliciesV2RegoMetadata) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	for k := range m.Metadata {

		if err := validate.Required("metadata"+"."+k, "body", m.Metadata[k]); err != nil {
			return err
		}
		if val, ok := m.Metadata[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metadata" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("metadata" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *PoliciesV2RegoMetadata) validateRules(formats strfmt.Registry) error {
	if swag.IsZero(m.Rules) { // not required
		return nil
	}

	for k := range m.Rules {

		if val, ok := m.Rules[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this policies v2 rego metadata based on the context it is used
func (m *PoliciesV2RegoMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PoliciesV2RegoMetadata) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Metadata {

		if val, ok := m.Metadata[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *PoliciesV2RegoMetadata) contextValidateRules(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Rules {

		if val, ok := m.Rules[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PoliciesV2RegoMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoliciesV2RegoMetadata) UnmarshalBinary(b []byte) error {
	var res PoliciesV2RegoMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
