// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PoliciesV2PolicyOverlayID policies v2 policy overlay ID
//
// swagger:model policies.v2.PolicyOverlayID
type PoliciesV2PolicyOverlayID struct {

	// context
	// Required: true
	Context *string `json:"context"`

	// type
	// Required: true
	Type *string `json:"type"`
}

// Validate validates this policies v2 policy overlay ID
func (m *PoliciesV2PolicyOverlayID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PoliciesV2PolicyOverlayID) validateContext(formats strfmt.Registry) error {

	if err := validate.Required("context", "body", m.Context); err != nil {
		return err
	}

	return nil
}

func (m *PoliciesV2PolicyOverlayID) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this policies v2 policy overlay ID based on context it is used
func (m *PoliciesV2PolicyOverlayID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoliciesV2PolicyOverlayID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoliciesV2PolicyOverlayID) UnmarshalBinary(b []byte) error {
	var res PoliciesV2PolicyOverlayID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
