// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PoliciesV2PoliciesUnderRoot policies v2 policies under root
//
// swagger:model policies.v2.PoliciesUnderRoot
type PoliciesV2PoliciesUnderRoot struct {

	// files
	Files map[string]PoliciesV2MultiVersionFileInfo `json:"files,omitempty"`

	// namespace
	Namespace map[string]PoliciesV2MultiVersionPackageInfo `json:"namespace,omitempty"`
}

// Validate validates this policies v2 policies under root
func (m *PoliciesV2PoliciesUnderRoot) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFiles(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNamespace(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PoliciesV2PoliciesUnderRoot) validateFiles(formats strfmt.Registry) error {
	if swag.IsZero(m.Files) { // not required
		return nil
	}

	for k := range m.Files {

		if err := validate.Required("files"+"."+k, "body", m.Files[k]); err != nil {
			return err
		}
		if val, ok := m.Files[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("files" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("files" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *PoliciesV2PoliciesUnderRoot) validateNamespace(formats strfmt.Registry) error {
	if swag.IsZero(m.Namespace) { // not required
		return nil
	}

	for k := range m.Namespace {

		if err := validate.Required("namespace"+"."+k, "body", m.Namespace[k]); err != nil {
			return err
		}
		if val, ok := m.Namespace[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("namespace" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("namespace" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this policies v2 policies under root based on the context it is used
func (m *PoliciesV2PoliciesUnderRoot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFiles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNamespace(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PoliciesV2PoliciesUnderRoot) contextValidateFiles(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Files {

		if val, ok := m.Files[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *PoliciesV2PoliciesUnderRoot) contextValidateNamespace(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Namespace {

		if val, ok := m.Namespace[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PoliciesV2PoliciesUnderRoot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoliciesV2PoliciesUnderRoot) UnmarshalBinary(b []byte) error {
	var res PoliciesV2PoliciesUnderRoot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
