// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PoliciesV2PolicyFile policies v2 policy file
//
// swagger:model policies.v2.PolicyFile
type PoliciesV2PolicyFile struct {

	// content
	Content string `json:"content,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// revision
	Revision string `json:"revision,omitempty"`
}

// Validate validates this policies v2 policy file
func (m *PoliciesV2PolicyFile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policies v2 policy file based on context it is used
func (m *PoliciesV2PolicyFile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoliciesV2PolicyFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoliciesV2PolicyFile) UnmarshalBinary(b []byte) error {
	var res PoliciesV2PolicyFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
