// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PoliciesV2RuleMetadata policies v2 rule metadata
//
// swagger:model policies.v2.RuleMetadata
type PoliciesV2RuleMetadata struct {

	// error
	Error string `json:"error,omitempty"`

	// value
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this policies v2 rule metadata
func (m *PoliciesV2RuleMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policies v2 rule metadata based on context it is used
func (m *PoliciesV2RuleMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoliciesV2RuleMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoliciesV2RuleMetadata) UnmarshalBinary(b []byte) error {
	var res PoliciesV2RuleMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
